# Generated by Django 2.1.7 on 2019-03-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190310_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('Persmissão1', 'User tem Permissão 1'), ('Persmissão2', 'User tem Permissão 2'), ('Persmissão3', 'User tem Permissão 3'))},
        ),
    ]
