# Generated by Django 2.1.7 on 2019-03-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190311_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('Persmissão1', 'User tem Permissão 1'), ('ver_dashboard', 'User pode ver Dashboard'), ('Persmissão3', 'User tem Permissão 3'))},
        ),
    ]
