# Generated by Django 2.1.7 on 2019-03-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20190309_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdopedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itensdopedido',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
